### ISSUE TITLE
test succeeds even when config cannot be read properly

### ISSUE THREAD

**Issue by gosuto-inzasheru** [lakuapik/gh-actions-http-status#1]
why the config is not read properly i havent found out yet, but either way i think the situation below should not result in a successful test

either the parse error should raise completely, or an empty array should not result in a success?

```
==Starting gh-actions HTTP Status==

jq: parse error: Expected another array element at line 1, column 120

HTTP Status result: Success

==END==
```

**Comment by gosuto-inzasheru** [comment]
i think what happened in this case is that the `steps.deploy.outputs.url` var did not exist..

```
      - name: Confirm deployed HTTP status code
        uses: "lakuapik/gh-actions-http-status@v1"
        with:
          sites: '["${{ steps.deploy.outputs.url }}"]'
          expected: "[200]"
```
